### PR TITLE
Patches from mono

### PR DESCRIPTION
**Pull request by sancheolz**
The code is synchronized with the mono repository. I need a new release of your nuget package with net6 support, so I suggest starting with the following patches

### CODE REVIEW

**Comment by DanielVanNoord** [comment]
Does this contain changes that are not in the main mono repository? For example I can't find any changes to PropertyTab in the main mono repository (https://github.com/mono/mono/blob/main/mcs/class/System.Windows.Forms/System.Windows.Forms.PropertyGridInternal/PropertiesTab.cs)

**Comment by sancheolz** [comment]
Yes, some changes not existing in mono repository. This changes came from our fork of mono repo and was ported to yours project. I can explain any change that not in upstream mono

**Comment by DanielVanNoord** [comment]
Over the changes look good. I have been trying to be identical to upstream mono however it looks like that is pretty dead now. I am going to merge this and do some tests on getting out a .Net 6 release.
If you can send in a pull request to mono with the same fixes that would be great. It looks like you have contributed there before.

**Comment by sancheolz** [comment]
Thank you. I will send missing changes in PR to mono. By the way some changes already waiting in PRs.

**Comment by sancheolz** [comment]
As a result, I have to send requests for these files
```
System.Windows.Forms.PropertyGridInternal/PropertiesTab.cs
System.Windows.Forms/GridEntry.cs
System.Windows.Forms/GridItemCollection.cs
System.Windows.Forms/PropertyGrid.cs
System.Windows.Forms/TreeView.cs
```

**Pull request merged**
